import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header' // Header 컴포넌트 import // ClerkProvider import

// 참고: Geist 폰트 정의가 누락되어 있어 안전하게 추가합니다.
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // 1. ClerkProvider를 최상위 컴포넌트로 사용하여 모든 페이지를 감쌉니다.
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* 2. Header 컴포넌트를 children (페이지 내용) 위에 배치합니다. */}
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
